<template>
  <div class="recommand">
    <h2>商品推荐</h2>
    <ul>
      <li>recommand1</li>
      <li>recommand2</li>
      <li>recommand3</li>
      <li>recommand4</li>
      <li>recommand5</li>
      <li>recommand6</li>
      <li>recommand7</li>
      <li>recommand8</li>
      <li>recommand9</li>
      <li>recommand10</li>
      <li>recommand11</li>
      <li>recommand12</li>
      <li>recommand13</li>
      <li>recommand14</li>
      <li>recommand15</li>
      <li>recommand16</li>
      <li>recommand17</li>
      <li>recommand18</li>
      <li>recommand19</li>
      <li>recommand20</li>
      <li>recommand21</li>
      <li>recommand22</li>
      <li>recommand23</li>
      <li>recommand24</li>
      <li>recommand25</li>
      <li>recommand26</li>
      <li>recommand27</li>
      <li>recommand28</li>
      <li>recommand29</li>
      <li>recommand30</li>
      <li>recommand31</li>
      <li>recommand32</li>
      <li>recommand33</li>
      <li>recommand34</li>
      <li>recommand35</li>
      <li>recommand36</li>
      <li>recommand37</li>
      <li>recommand38</li>
      <li>recommand39</li>
      <li>recommand40</li>
      <li>recommand41</li>
      <li>recommand42</li>
      <li>recommand43</li>
      <li>recommand44</li>
      <li>recommand45</li>
      <li>recommand46</li>
      <li>recommand47</li>
      <li>recommand48</li>
      <li>recommand49</li>
      <li>recommand50</li>
      <li>recommand51</li>
      <li>recommand52</li>
      <li>recommand53</li>
      <li>recommand54</li>
      <li>recommand55</li>
      <li>recommand56</li>
      <li>recommand57</li>
      <li>recommand58</li>
      <li>recommand59</li>
      <li>recommand60</li>
      <li>recommand61</li>
      <li>recommand62</li>
      <li>recommand63</li>
      <li>recommand64</li>
      <li>recommand65</li>
      <li>recommand66</li>
      <li>recommand67</li>
      <li>recommand68</li>
      <li>recommand69</li>
      <li>recommand70</li>
      <li>recommand71</li>
      <li>recommand72</li>
      <li>recommand73</li>
      <li>recommand74</li>
      <li>recommand75</li>
      <li>recommand76</li>
      <li>recommand77</li>
      <li>recommand78</li>
      <li>recommand79</li>
      <li>recommand80</li>
      <li>recommand81</li>
      <li>recommand82</li>
      <li>recommand83</li>
      <li>recommand84</li>
      <li>recommand85</li>
      <li>recommand86</li>
      <li>recommand87</li>
      <li>recommand88</li>
      <li>recommand89</li>
      <li>recommand90</li>
      <li>recommand91</li>
      <li>recommand92</li>
      <li>recommand93</li>
      <li>recommand94</li>
      <li>recommand95</li>
      <li>recommand96</li>
      <li>recommand97</li>
      <li>recommand98</li>
      <li>recommand99</li>
      <li>recommand100</li>
      <li>recommand101</li>
      <li>recommand102</li>
      <li>recommand103</li>
      <li>recommand104</li>
      <li>recommand105</li>
      <li>recommand106</li>
      <li>recommand107</li>
      <li>recommand108</li>
      <li>recommand109</li>
      <li>recommand110</li>
      <li>recommand111</li>
      <li>recommand112</li>
      <li>recommand113</li>
      <li>recommand114</li>
      <li>recommand115</li>
      <li>recommand116</li>
      <li>recommand117</li>
      <li>recommand118</li>
      <li>recommand119</li>
      <li>recommand120</li>
      <li>recommand121</li>
      <li>recommand122</li>
      <li>recommand123</li>
      <li>recommand124</li>
      <li>recommand125</li>
      <li>recommand126</li>
      <li>recommand127</li>
      <li>recommand128</li>
      <li>recommand129</li>
      <li>recommand130</li>
      <li>recommand131</li>
      <li>recommand132</li>
      <li>recommand133</li>
      <li>recommand134</li>
      <li>recommand135</li>
      <li>recommand136</li>
      <li>recommand137</li>
      <li>recommand138</li>
      <li>recommand139</li>
      <li>recommand140</li>
      <li>recommand141</li>
      <li>recommand142</li>
      <li>recommand143</li>
      <li>recommand144</li>
      <li>recommand145</li>
      <li>recommand146</li>
      <li>recommand147</li>
      <li>recommand148</li>
      <li>recommand149</li>
      <li>recommand150</li>
      <li>recommand151</li>
      <li>recommand152</li>
      <li>recommand153</li>
      <li>recommand154</li>
      <li>recommand155</li>
      <li>recommand156</li>
      <li>recommand157</li>
      <li>recommand158</li>
      <li>recommand159</li>
      <li>recommand160</li>
      <li>recommand161</li>
      <li>recommand162</li>
      <li>recommand163</li>
      <li>recommand164</li>
      <li>recommand165</li>
      <li>recommand166</li>
      <li>recommand167</li>
      <li>recommand168</li>
      <li>recommand169</li>
      <li>recommand170</li>
      <li>recommand171</li>
      <li>recommand172</li>
      <li>recommand173</li>
      <li>recommand174</li>
      <li>recommand175</li>
      <li>recommand176</li>
      <li>recommand177</li>
      <li>recommand178</li>
      <li>recommand179</li>
      <li>recommand180</li>
      <li>recommand181</li>
      <li>recommand182</li>
      <li>recommand183</li>
      <li>recommand184</li>
      <li>recommand185</li>
      <li>recommand186</li>
      <li>recommand187</li>
      <li>recommand188</li>
      <li>recommand189</li>
      <li>recommand190</li>
      <li>recommand191</li>
      <li>recommand192</li>
      <li>recommand193</li>
      <li>recommand194</li>
      <li>recommand195</li>
      <li>recommand196</li>
      <li>recommand197</li>
      <li>recommand198</li>
      <li>recommand199</li>
      <li>recommand200</li>
    </ul>
  </div>
</template>

<script>
  export default {
    name: "ProductRecommand"
  }
</script>

<style scoped>
  .recommand {
    background-color: #ff0;
  }
  .recommand h2 {
    text-align: center;
  }
</style>
